apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-node-server
  labels:
    app: simple-node-server
spec:
  selector:
    matchLabels:
      app: simple-node-server
  replicas: 10
  template:
    metadata:
      labels:
        app: "simple-node-server"
    spec:
      containers:
        - name: simple-node-server
          image: gabrielmalenowitch/simple-node-server